version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      development-dependencies:
        dependency-type: development
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major
      - dependency-name: "@commitlint/config-conventional"
        update-types:
          - version-update:semver-major
      - dependency-name: "@commitlint/lint"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
