name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions: {}

jobs:
  release:
    if: github.repository == 'robertosousa1/replace-special-characters'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
